baseURL: "https://kubamartin.com/"
title: Jacob Martin
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableInlineShortcodes: true
enableEmoji: true

googleAnalytics: UA-74339391-1

minify:
    disableXML: true
    minifyOutput: true

params:
    showAllPagesInArchive: true
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Jacob Martin
    keywords: [Blog, Portfolio]
    author: Jacob Martin
    # author: ["Me", "You"] # multiple authors
    images: ["images/avatar.jpg"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    #assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
    #    favicon: "<link / abs url>"
    #    favicon16x16: "<link / abs url>"
    #    favicon32x32: "<link / abs url>"
    #    apple_touch_icon: "<link / abs url>"
    #    safari_pinned_tab: "<link / abs url>"

    label:
        text: "Jacob Martin"

    # home-info mode
    homeInfoParams:
        Title: "Hey there! \U0001F44B"
        Content: |
          I'm Kuba (short for Jacob), a Software Engineer with experience working in high scale distributed systems environments.

          I've got a practical mindset of shipping, and building projects in as simple a way - but not simpler - as possible.

          I've got experience with most of the widely used programming paradigms, and fancy trying out new ones, though so far I'm mostly finding myself using Go professionaly.

          On the side I develop [OctoSQL](https://github.com/cube2222/octosql), a SQL execution engine as CLI which lets you query multiple datasources and files simultaneously using SQL.

          At some point I've also created [jql](https://github.com/cube2222/jql), which is meant to be a simpler and more uniform (lispy) alternative to jq. It may seem dead on first glance, but it's simply finished. I'm using it daily.

    socialIcons:
        - name: github
          url: "https://github.com/cube2222"
        - name: linkedin
          url: "https://linkedin.com/in/jakubmartin/"
        - name: twitter
          url: https://twitter.com/cube2222_2

#    analytics:
#        google:
#            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/cube2222/cube2222.github.io/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - name: Archive
          url: archive
          weight: 10
        - identifier: about-me
          name: About Me
          url: /
          weight: 5

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
